### ISSUE TITLE
New TIKTOK API Requirement

### ISSUE THREAD

**Issue by sarabhi92git** [ssovit/TikTok-Video-No-Watermark-Download#1]
Hi, I have seen you are using your domain name in api url. 

I would like to purchase if you provide the new tiktok api url in code itself rather than using your web url for calling tiktok api.

let me know if available

**Comment by ssovit** [comment]
This script is free PHP package provided for buyers of https://codecanyon.net/item/tiktok-video-downloader-wordpress-plugin/26370715 and requires purchase code activation to function.

The API source code isn't available for sale. 

But you can use https://github.com/ssovit/TikTok-Video-Downloader-RapidAPI that connects to RapidAPI endpoints at https://rapidapi.com/wppressapi-wppressapi-default/api/tiktok9

**Comment by ssovit** [comment]
If you want to, I can sell the code done in NodeJS/ExpressJS for a price. contact me on my email from my profile.

**Comment by sarabhi92git** [comment]
HI @ssovit , I have just sent you an email to buy the Source code of API to download videos without watermarks.

Please check it and confirm

**Comment by ssovit** [comment]
> HI @ssovit , I have just sent you an email to buy the Source code of API to download videos without watermarks.
> 
> Please check it and confirm

didn't get your reply

**Comment by sarabhi92git** [comment]
> > HI @ssovit , I have just sent you an email to buy the Source code of API to download videos without watermarks.
> > Please check it and confirm
> 
> didn't get your reply

Check again, I have sent you
